spring:
  profiles:
    group:
      "local": "testdb,common"
      "dev":  "testdb,common"
      "prod": "proddb,common"

---

### COMMON
spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

---

### LOCAL
spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: membership
    password: membership


  ## JPA 관련 설정
  jpa:
    generate-ddl: true # -- 자동으로 엔티티와 테이블을 맞출 것인가? (true/false)
    hibernate:
      ddl-auto: validate # -- 자동으로 엔티티와 테이블을 맞출 것인가? (none/create-drop/create/update/validate)
    show-sql: true
    open-in-view: false # -- 영속성을 컨트롤러 영역까지 가져갈 것인가? (false:서비스 영역까지만 유지할 것인가?)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true # -- Pretty Log

  h2:
    console:
      enabled: true

# -- hibernate 로그의 '?'에 어떤 값이 들어갔는지 보여준다.
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

---

### DEV