server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: membership
    password: membership

  ## JPA 관련 설정
  jpa:
    database: mariadb
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate


  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace